version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "FLASK_DEBUG=1 flask --app core.app run --host=0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
